"use client";
import { useState,useTransition } from "react";
import { activateWalkInCode,generateWalkInCodes } from "@/app/actions/walk-in-codes";
export default function WalkInsPage(){
 const[programmeId,setProgrammeId]=useState("");const[count,setCount]=useState(50);const[code,setCode]=useState("");const[codes,setCodes]=useState<string[]>([]);const[message,setMessage]=useState("");const[pending,start]=useTransition();
 const input="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900";
 function generate(){setMessage("");start(async()=>{const result=await generateWalkInCodes(programmeId,count);if(!result.ok){setMessage(result.error);return;}setCodes(result.codes);setMessage(`${result.codes.length} unused codes generated. Download them now for printing.`);});}
 function activate(){setMessage("");start(async()=>{const result=await activateWalkInCode(programmeId,code.toUpperCase());if(!result.ok){setMessage(result.error);return;}setMessage(`Code ${result.participant.screeningReference} registered successfully.`);setCode("");});}
 function download(){const csv="Code\\n"+codes.join("\\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const link=document.createElement("a");link.href=url;link.download="pulse80-walk-in-codes.csv";link.click();URL.revokeObjectURL(url);}
 return <main className="mx-auto max-w-3xl space-y-6 p-6"><h1 className="text-2xl font-semibold text-navy">Walk-in registration</h1><p className="text-sm text-slate-600">Generate unpredictable four-character codes before the event. Register each code when its participant arrives. Registration does not mean screening is completed.</p><label className="block space-y-2 text-sm font-medium">Programme ID<input className={input+" w-full"} value={programmeId} onChange={e=>setProgrammeId(e.target.value)} placeholder="Programme UUID"/></label><section className="space-y-3 rounded-xl border p-4"><h2 className="font-semibold">Prepare printed codes</h2><label className="flex items-center gap-3 text-sm">Number of codes<input className={input+" w-28"} type="number" min={1} max={2000} value={count} onChange={e=>setCount(Number(e.target.value))}/></label><button className="rounded-lg bg-primary px-4 py-2 text-sm text-white disabled:opacity-50" disabled={pending||!programmeId||count<1||count>2000} onClick={generate}>Generate codes</button>{codes.length>0?<div className="space-y-2"><button className="rounded-lg border px-4 py-2 text-sm" onClick={download}>Download printable CSV</button><p className="text-xs text-slate-600">Keep the code list secure. Codes are unused until registered.</p></div>:null}</section><section className="space-y-3 rounded-xl border p-4"><h2 className="font-semibold">Register arriving participant</h2><input className={input+" w-full uppercase"} maxLength={4} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Four-character code"/><button className="rounded-lg bg-primary px-4 py-2 text-sm text-white disabled:opacity-50" disabled={pending||!programmeId||code.length!==4} onClick={activate}>Activate code</button></section>{message?<p role="status" className="rounded-lg bg-slate-100 p-3 text-sm">{message}</p>:null}</main>;
}
