"use client";
import { useEffect, useState, useTransition } from "react";
import { loadOrganisationUnits, saveOrganisationUnit, type OrganisationUnit } from "@/app/actions/organisation-units";
export function OrganisationUnits({ organisationId }: { organisationId: string }) {
  const [units, setUnits] = useState<OrganisationUnit[]>([]); const [editing, setEditing] = useState<OrganisationUnit | null>(null); const [kind, setKind] = useState<"branch" | "department">("branch"); const [message, setMessage] = useState("Loading branches and departments…"); const [pending, start] = useTransition();
  useEffect(() => { let active = true; void loadOrganisationUnits(organisationId).then(rows => { if (active) { setUnits(rows); setMessage(""); } }).catch(() => { if (active) setMessage("Could not load branches and departments."); }); return () => { active = false; }; }, [organisationId]);
  const control = "rounded-lg border border-card-border px-3 py-2 text-sm";
  return <div className="space-y-4"><h2 className="font-semibold">Branches & Departments</h2>{message && <p role="status" className="text-sm">{message}</p>}
    <form key={editing?.id ?? kind} className="grid gap-3 md:grid-cols-2" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); start(async () => { const result = await saveOrganisationUnit(editing?.id ?? null, { organisationId, kind, parentId: kind === "department" ? String(data.get("parent")) : null, name: String(data.get("name")), location: String(data.get("location")), employees: Number(data.get("employees")), status: String(data.get("status")) }); if (!result.ok) { setMessage(result.error); return; } try { setUnits(await loadOrganisationUnits(organisationId)); setEditing(null); form.reset(); setMessage("Saved."); } catch { setMessage("Saved, but the list could not refresh. Reload the page."); } }); }}>
      <label className="grid gap-1 text-sm">Type<select className={control} disabled={Boolean(editing) || pending} value={kind} onChange={event => setKind(event.target.value as "branch" | "department")}><option value="branch">Branch</option><option value="department">Department</option></select></label>
      {kind === "department" && <label className="grid gap-1 text-sm">Branch<select required name="parent" defaultValue={editing?.parentId ?? ""} className={control}><option value="">Choose branch</option>{units.filter(unit => unit.kind === "branch").map(unit => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label>}
      <label className="grid gap-1 text-sm">Name<input required minLength={2} maxLength={160} name="name" defaultValue={editing?.name} className={control} /></label><label className="grid gap-1 text-sm">Location<input name="location" maxLength={500} defaultValue={editing?.location} className={control} /></label><label className="grid gap-1 text-sm">Employees<input required name="employees" type="number" min={0} max={10000000} defaultValue={editing?.employees ?? 0} className={control} /></label><label className="grid gap-1 text-sm">Status<select name="status" defaultValue={editing?.status ?? "Active"} className={control}>{["Active", "Paused", "Archived"].map(value => <option key={value}>{value}</option>)}</select></label><div className="flex gap-2"><button disabled={pending} className={control}>{pending ? "Saving…" : editing ? "Save changes" : "Add"}</button>{editing && <button type="button" className={control} onClick={() => setEditing(null)}>Cancel</button>}</div>
    </form>
    {units.map(unit => <div key={unit.id} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3 text-sm"><span>{unit.name} · {unit.kind}{unit.parentId ? ` · ${units.find(parent => parent.id === unit.parentId)?.name ?? "Branch"}` : ""} · {unit.employees} employees · {unit.status}</span><button className={control} onClick={() => { setKind(unit.kind); setEditing(unit); }}>Edit</button></div>)}
  </div>;
}
